In [5]:
import numpy as np
np.array([1, 2, 3])

array([1, 2, 3])

Docstring shortcut 'Shift + Tab'

In [2]:
odd_number_list = [1, 3, 5, 7]

In [3]:
np.array(odd_number_list)

array([1, 3, 5, 7])

In [4]:
two_dim_list = [[1, 1, 1], [2, 2, 2], [3, 3, 3]]
np.array(two_dim_list)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [8]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [9]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.linspace(0, 5, 5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [17]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [18]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [21]:
np.random.rand(3)

array([0.14101207, 0.32959868, 0.58270825])

In [22]:
np.random.rand(7)

array([0.7631959 , 0.53768095, 0.61494519, 0.20533555, 0.38326783,
       0.0700069 , 0.0513008 ])

In [23]:
np.random.rand(3, 4)

array([[0.06987888, 0.22493423, 0.12707533, 0.49913505],
       [0.30804764, 0.49060344, 0.83973792, 0.56125706],
       [0.71462247, 0.78478768, 0.35781   , 0.06264186]])

In [24]:
np.random.randn(3)

array([-0.2984677 , -0.00307331, -0.64624497])

In [25]:
np.random.randn(5)

array([-0.75226366,  0.11212467, -0.43784661, -0.9545847 , -0.19355369])

In [26]:
np.random.randn(3, 5)

array([[-1.6277742 ,  0.61919897,  0.13483193, -1.94253323, -0.50680116],
       [-0.50181039,  0.74483842,  1.40835543, -0.34762313, -0.3381502 ],
       [-0.49764163, -0.13686985,  0.28372098,  1.2162985 , -0.09551837]])

In [27]:
np.random.randint(0, 50, 20)

array([13,  6, 13, 31, 43, 12, 28,  2, 15, 32, 19, 34, 30, 43, 10, 22, 11,
       11,  0, 46])

In [28]:
rand_arr = np.random.randint(0, 50, 20)

In [29]:
rand_arr

array([36,  0,  4, 34, 33, 45,  0, 45, 10,  1,  5,  2,  0, 47,  1,  0, 42,
       23, 32, 33])

In [44]:
second_arr = np.arange(20)

In [45]:
second_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [32]:
rand_arr.reshape(4, 5)

array([[36,  0,  4, 34, 33],
       [45,  0, 45, 10,  1],
       [ 5,  2,  0, 47,  1],
       [ 0, 42, 23, 32, 33]])

In [34]:
rand_arr.reshape(5, 4)

array([[36,  0,  4, 34],
       [33, 45,  0, 45],
       [10,  1,  5,  2],
       [ 0, 47,  1,  0],
       [42, 23, 32, 33]])

In [39]:
second_arr.reshape(2, 10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [36]:
second_arr.max()

19

In [37]:
second_arr.min()

0

In [38]:
second_arr.argmax()

19

In [46]:
rand_arr.max()

47

In [47]:
rand_arr.argmax()

13

In [48]:
rand_arr.min()

0

In [49]:
rand_arr.argmin()

1

In [50]:
second_arr.shape

(20,)

In [51]:
reshaped_arr = second_arr.reshape(2, 10)

In [52]:
reshaped_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [53]:
reshaped_arr.shape

(2, 10)

In [54]:
reshaped_arr.dtype

dtype('int64')