In [1]:
import numpy as np
np.array([1, 2, 3])

array([1, 2, 3])

Docstring shortcut 'Shift + Tab'

In [2]:
odd_number_list = [1, 3, 5, 7]

In [3]:
np.array(odd_number_list)

array([1, 3, 5, 7])

In [4]:
two_dim_list = [[1, 1, 1], [2, 2, 2], [3, 3, 3]]
np.array(two_dim_list)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [5]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [6]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.linspace(0, 5, 5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [13]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [14]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [17]:
np.random.rand(3)

array([0.02083964, 0.39178475, 0.31433413])

In [18]:
np.random.rand(7)

array([0.79222891, 0.40127139, 0.54828729, 0.00355295, 0.87288807,
       0.68077234, 0.33902445])

In [19]:
np.random.rand(3, 4)

array([[0.39936869, 0.38704124, 0.16508612, 0.75923335],
       [0.83833946, 0.93786712, 0.98122877, 0.57551501],
       [0.89013728, 0.20099856, 0.03010039, 0.17227824]])

In [20]:
np.random.randn(3)

array([-0.48612856, -0.65108119, -0.15312319])

In [21]:
np.random.randn(5)

array([-1.76425863,  0.89978503,  0.07462505, -1.89021757,  1.2648324 ])

In [22]:
np.random.randn(3, 5)

array([[-1.10042708,  0.9470882 , -0.54003952,  0.27484802, -0.19733212],
       [-0.94266563, -0.03963699, -1.04511406, -0.39286889,  0.91723009],
       [ 0.44498925,  0.31025842, -0.39379502, -0.13537463, -0.16435316]])

In [23]:
np.random.randint(0, 50, 20)

array([46,  6,  2, 33, 46, 19, 39, 24, 29, 26, 33,  1,  8, 10, 47, 23, 16,
       31,  3, 29])

In [24]:
rand_arr = np.random.randint(0, 50, 20)

In [25]:
rand_arr

array([ 9, 15, 43, 42, 12, 25, 12, 18, 40, 37, 46, 45, 38, 25, 40, 38, 27,
       41, 37, 44])

In [26]:
second_arr = np.arange(20)

In [27]:
second_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [28]:
rand_arr.reshape(4, 5)

array([[ 9, 15, 43, 42, 12],
       [25, 12, 18, 40, 37],
       [46, 45, 38, 25, 40],
       [38, 27, 41, 37, 44]])

In [29]:
rand_arr.reshape(5, 4)

array([[ 9, 15, 43, 42],
       [12, 25, 12, 18],
       [40, 37, 46, 45],
       [38, 25, 40, 38],
       [27, 41, 37, 44]])

In [30]:
second_arr.reshape(2, 10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [31]:
second_arr.max()

19

In [32]:
second_arr.min()

0

In [33]:
second_arr.argmax()

19

In [34]:
rand_arr.max()

46

In [35]:
rand_arr.argmax()

10

In [36]:
rand_arr.min()

9

In [37]:
rand_arr.argmin()

0

In [38]:
second_arr.shape

(20,)

In [39]:
reshaped_arr = second_arr.reshape(2, 10)

In [40]:
reshaped_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [41]:
reshaped_arr.shape

(2, 10)

In [42]:
reshaped_arr.dtype

dtype('int64')