In [1]:
import numpy as np

In [2]:
int_arr = np.random.randint(0, 10, 10)

In [3]:
int_arr

array([8, 3, 1, 0, 6, 1, 0, 4, 2, 3])

In [4]:
int_arr[0]

8

In [5]:
int_arr[9]

3

In [6]:
int_arr[1:3]

array([3, 1])

In [7]:
int_arr[1:7]

array([3, 1, 0, 6, 1, 0])

In [8]:
int_arr[0:4]

array([8, 3, 1, 0])

In [9]:
int_arr[:4]

array([8, 3, 1, 0])

In [10]:
int_arr[4:10]

array([6, 1, 0, 4, 2, 3])

In [11]:
int_arr[4:]

array([6, 1, 0, 4, 2, 3])

In [12]:
int_arr[4:10] = 10

In [13]:
int_arr

array([ 8,  3,  1,  0, 10, 10, 10, 10, 10, 10])

In [14]:
arr = np.arange(0, 10)

In [15]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
new_arr = arr[:4]

In [17]:
new_arr

array([0, 1, 2, 3])

In [18]:
new_arr[2:] = 7

In [19]:
new_arr

array([0, 1, 7, 7])

In [20]:
arr

array([0, 1, 7, 7, 4, 5, 6, 7, 8, 9])

In [21]:
arr = np.arange(0, 10)

In [22]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
new_arr = arr.copy()

In [24]:
new_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
new_arr[:] = 0

In [26]:
new_arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [29]:
bool_arr = arr > 6

In [30]:
bool_arr

array([False, False, False, False, False, False, False,  True,  True,
        True])

In [31]:
arr[bool_arr]

array([7, 8, 9])

In [32]:
bool_arr = arr > 0

In [33]:
arr[bool_arr]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr[arr > 0]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arr[arr < 5]

array([0, 1, 2, 3, 4])